/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pepelopolis;

/**
 *
 * @author carlospanohernandez
 */
public class VentanaSeleccion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSeleccion
     */
    public VentanaSeleccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selecciona tu película");
        setSize(new java.awt.Dimension(875, 500));
        getContentPane().setLayout(null);

        jButton5.setBackground(new java.awt.Color(41, 76, 151));
        jButton5.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(236, 181, 42));
        jButton5.setText("Ready Player One");
        getContentPane().add(jButton5);
        jButton5.setBounds(620, 420, 150, 29);

        jButton6.setBackground(new java.awt.Color(41, 76, 151));
        jButton6.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(236, 181, 42));
        jButton6.setText("DeadPool");
        getContentPane().add(jButton6);
        jButton6.setBounds(110, 420, 150, 29);

        jButton7.setBackground(new java.awt.Color(41, 76, 151));
        jButton7.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(236, 181, 42));
        jButton7.setText("Avengers Infinity War");
        getContentPane().add(jButton7);
        jButton7.setBounds(360, 420, 150, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pepelopolis/FondoSeleccion.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 875, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSeleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
